Fixed heading within code-fence

diff --git a/tocgen b/tocgen
--- a/tocgen
+++ b/tocgen
@@ -33,13 +33,13 @@ gen_toc(){
     echo -e "${indent}- [${heading}](${link})  "
   done
   echo -n "#####   "
-} < <(grep -E '^[#]+ ' "${md_file}" | tr -d \\r)
+} < <(sed -nE '/^```/,/^```/!{/^[#]+ /p}' "${md_file}" | tr -d \\r)
 
 toc="$(gen_toc)" # Holds the TOC to be injected at the placeholder
 
 # Simulate in-place edit
-  buffer="$(cat "${md_file}")" # Hold the entire text from the file
-  trap 'rm -f ${tmpfile} 2>/dev/null' exit # Clean up in case of unforeseen/abrupt exit
-  tmpfile="$(mktemp)"
-  echo -n "${buffer//\[TOC\]  /"${toc}"}" > "${tmpfile}"
-  mv "${tmpfile}" "${md_file}"
+buffer="$(cat "${md_file}")" # Hold the entire text from the file
+trap 'rm -f ${tmpfile} 2>/dev/null' exit # Clean up in case of unforeseen/abrupt exit
+tmpfile="$(mktemp)"
+echo -n "${buffer//\[TOC\]  /"${toc}"}" > "${tmpfile}"
+mv "${tmpfile}" "${md_file}" && echo "Done" >&2
